from services.menus.menu_main import menu

print("BEM VINDO AO PROJETO DE ESTRUTURA DE DADOS!")
print("AQUI, ESTAMOS IMPLEMENTANDO AS SEGUINTES ESTRUTURAS DE DADOS: LISTA, FILA, PILHA, ORDENAÇÃO DE DADOS E ALGORÍTMOS DE BUSCA")
print("ESCOLHA QUAL DESEJA COMEÇAR A TESTAR: ")

menu()